version: 2
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet
    - 1280  # Desktop
  min-height: 1024
  percy-css: |
    /* Hide elements that cause flakiness */
    [data-testid="loading-spinner"] {
      visibility: hidden;
    }
    /* Hide dynamic timestamps */
    time, [data-testid="timestamp"] {
      visibility: hidden;
    }
